In [4]:
#1 dim array
import numpy as np
arr= np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [5]:
# 2 dim array
import numpy as np
arr= np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2


In [6]:
# 3 dim array
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
print(type(arr))
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
3


In [10]:
#Array indexing
import numpy as np
arr=np.array([[4,2,7],[3,6,4]])
print(arr[1,2])
print(arr.dtype)

b=np.array([[[0,8,1],[1,7,9]],[[2,4,8],[3,2,6]],[[8,9,4],[2,5,7]]])
print("Array Indexing: ",b[1,0,2])
print("Dimension of array: ",b.ndim)

4
int64
Array Indexing:  8
Dimension of array:  3


In [2]:
#array data type
import numpy as np
arr=np.array(['apple','banana','cherry'])
print(arr.dtype)

<U6


In [16]:
#coverting into different data type
import numpy as np
arr=np.array([1.7,0,3.9])
new_arr=arr.astype(bool)
print(new_arr)
print(type(new_arr))

[ True False  True]
<class 'numpy.ndarray'>


In [22]:
#copy and view
import numpy as np
a=np.array([1,2,3,4,5])
b=a.copy() #whatever changes that we make in orginal array doesn't affect the copy array
c=a.view() 
a[2]=8
print(a)
print(c)
print(b)

[1 2 8 4 5]
[1 2 8 4 5]
[1 2 3 4 5]


In [23]:
import numpy as np
a=np.array([1,2,3],ndmin=5)
print(a)
print("Shape of an array: ",a.shape)

[[[[[1 2 3]]]]]
Shape of an array:  (1, 1, 1, 1, 3)


In [27]:
#reshaping
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new=a.reshape(3,2,2)
print(new)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [36]:
#iteration
import numpy as np
arr=np.array([[1,2,3,4],[2,4,7,8]])
for a in arr:
    print(a) # this will give result in the array format only

for x in arr:
    for y in x:
        print(y) #this will give the array with each elements
        
print() # just for space

# to make this above step easier, which is to make lesser n for loops we can write
for a in np.nditer(arr):
    print(a)

[1 2 3 4]
[2 4 7 8]
1
2
3
4
2
4
7
8

1
2
3
4
2
4
7
8


In [37]:
import numpy as np
a=np.array([1,2,3,4])
for x in np.nditer(a,flags=['buffered'], op_dtypes=['S']):
    print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')


In [39]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,0]])
for x in np.nditer(a[:,::2]):
    print(x)

1
3
5
6
8
0


In [40]:
import numpy as np
arr=np.array([[2,3,4],[1,7,9]])
for i,x in np.ndenumerate(arr): #this basically helps you mention the corresponding index number along with the values
    print(i,x)

(0, 0) 2
(0, 1) 3
(0, 2) 4
(1, 0) 1
(1, 1) 7
(1, 2) 9


In [42]:
#joining
import numpy as np
a=np.array([1,2,3])
b=np.array([4,7,2])
new=np.concatenate((a,b))
print(new)

[1 2 3 4 7 2]


In [50]:
#array splitting
import numpy as np
a=np.array([1,2,3,8,0,6])
new=np.array_split(a,3)
print(new)
print(new[2])

[array([1, 2]), array([3, 8]), array([0, 6])]
[0 6]


In [51]:
import numpy as np
arr=np.array([2,4,5,8,7,1,0])
new=np.where(arr%2==0) #basically this gives you the indexes of even numbers
print(new)

(array([0, 1, 3, 6]),)


In [54]:
#filtering
import numpy as np
arr=np.array([30,31,32,33,34,35])
new_arr=[]
for element in arr:
    if element>31:
        new_arr.append(True)
    else:
        new_arr.append(False)

a=arr[new_arr]
print(arr)
print(a)

[30 31 32 33 34 35]
[32 33 34 35]


In [55]:
#filtering- using for loop
import numpy as np
arr=np.array([12,13,14,15,16,17])
new=[]
for i in arr:
    if i%2==0:
        new.append(True)
    else:
        new.append(False)
a=arr[new]
print("First array: ",arr)
print("Updated array: ",a)

First array:  [12 13 14 15 16 17]
Updated array:  [12 14 16]


In [56]:
#filtering direct way
import numpy as np
arr=np.array([2,3,4,5,6,7,9])
new=arr>4
updated_array=arr[new]
print(updated_array)

[5 6 7 9]


In [7]:
import numpy as np
arr1=np.arange(1,11)
arr2=np.array([[1,2,3],[4,5,6]])
arr3=np.zeros((3,3), dtype=int)
print(arr1)
print(arr2)
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 3]
 [4 5 6]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [13]:
arr = np.array([10, 20, 30, 40, 50])
arr[:2] #first 2 elements using slicing
arr[-3:] #last 3 elements
arr[::2] #every alternate number
arr[::-1] #reversed array

array([50, 40, 30, 20, 10])

In [16]:
import numpy as np
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
arr[1,:] #extracted second row
arr[:,0] #extracted first column
arr[2,1] #extracted 80
arr[0:2,0:2] #extracted first 2 rows and columns

array([[10, 20],
       [40, 50]])

In [17]:
# vectorization
arr = np.array([[1,2,3],
                [4,5,6]])
arr+[10,20,30]

array([[11, 22, 33],
       [14, 25, 36]])

In [20]:
#reshaping and flatteninh
arr = np.array([[1,2,3],
                [4,5,6]])
arr.ravel() #converted into 1-D array
arr.reshape(3,2) #converted into 3*2 array
arr.reshape(6,1) #converted into 1*6 array

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [23]:
arr = np.array([5, 12, 23, 4, 19, 8])
arr[arr<10]

array([5, 4, 8])

In [35]:
import numpy as np
arr=np.random.randint(1,51, size=10)
np.mean(arr)#mean
arr.max() #max value
arr.argmax() #index of max value
arr.reshape(2,5) 

array([[44, 14, 34, 31, 40],
       [35, 18, 23,  4, 42]], dtype=int32)

In [11]:
import numpy as np
arr = np.array([
    [12, 5, 20],
    [7, 30, 14],
    [25, 2, 9]
])
arr[arr>10]
arr[arr<10]=0
arr+[1,2,3]
arr.flatten()
# np.vstack((arr, [100,200,300])) 
np.concatenate((arr,np.array([100,200,300]).reshape(3,1)), axis=1)
# np.hstack((np.array([1,2,3]).reshape(3,1),arr))

array([[ 12,   0,  20, 100],
       [  0,  30,  14, 200],
       [ 25,   0,   0, 300]])

In [15]:
# adding a new column
arr = np.array([[1,2],[3,4],[5,6]])
np.hstack((arr,np.array([10,20,30]).reshape(3,1)))

array([[ 1,  2, 10],
       [ 3,  4, 20],
       [ 5,  6, 30]])

In [21]:
#matrix multiplication
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

A@B #1 method
np.dot(A,B) #2nd method
np.matmul(A,B) #3rd method

array([[19, 22],
       [43, 50]])

In [2]:
import numpy as np
arr=np.random.randint(1,101, size=(5,5))
arr[arr%2==0] #all even numbers
arr[arr>50]=999 #replacing
arr.max(axis=1) #max from each row
arr.sum(axis=0) #sum of each row
arr.flatten() #1-D array

In [44]:
import numpy as np
arr=np.random.randint(1,101, size=20)

new=arr.reshape(4,5)
print(new)
print()

rows=new[:2,:] #first 2 rows
print(rows)
print()

cols=new[:,-2:]
print(cols)
print()

new2=np.vstack((new,np.array([999,999,999,999,999])))
print(new2)
print()

addedrow=np.array_split(new2,2, axis=1)
print(addedrow)

[[33 73 16  7 89]
 [68 85 48 16 11]
 [66 60 51 25 18]
 [23 14 24 49 20]]

[[33 73 16  7 89]
 [68 85 48 16 11]]

[[ 7 89]
 [16 11]
 [25 18]
 [49 20]]

[[ 33  73  16   7  89]
 [ 68  85  48  16  11]
 [ 66  60  51  25  18]
 [ 23  14  24  49  20]
 [999 999 999 999 999]]

[array([[ 33,  73,  16],
       [ 68,  85,  48],
       [ 66,  60,  51],
       [ 23,  14,  24],
       [999, 999, 999]]), array([[  7,  89],
       [ 16,  11],
       [ 25,  18],
       [ 49,  20],
       [999, 999]])]


In [62]:
#Matrix multiplication
A=np.array([[1,2,3],
            [4,5,6]])
            
B=np.array([[10,20],
            [30,40],
            [50,60]])
C=A@B
print("Matrix multiplication:")
print(C)
print()

trans=C.T
print("Transpose: ")
print(trans)
print()

m=trans.mean()
print("Mean: ",m)
print()

square=trans**2
print("squared: ")
print(square)

Matrix multiplication:
[[220 280]
 [490 640]]

Transpose: 
[[220 490]
 [280 640]]

Mean:  407.5

squared: 
[[ 48400 240100]
 [ 78400 409600]]


In [82]:
import numpy as np
arr=np.random.randint(0,101,size=(5,5)) # 5*5 matrix generated
print(arr)
print()

print("Avg marks of each student: ")
avg=arr.mean(axis=1)
print(avg)
print()

print("Avg marks in each subject: ")
avg_marks=arr.mean(axis=0)
print(avg_marks)
print()

print("Overall average: ")
all_avg=arr.mean()
print(all_avg)
print()

print("Replacing all values below  40 with 0: ")
arr[arr<40]=0
print(arr)
print()

print("Total marks added: ")
total=arr.sum(axis=1)
total.reshape(5*1)
final=np.hstack((arr,total.reshape(5,1)))
print(final)
print()

print("1-D array: ")
print(arr.flatten())

[[ 32  15  29  23  59]
 [ 68  15  67   3  96]
 [  2  89  21  82  62]
 [100  89  62  75  48]
 [ 43  58  69  15  10]]

Avg marks of each student: 
[31.6 49.8 51.2 74.8 39. ]

Avg marks in each subject: 
[49.  53.2 49.6 39.6 55. ]

Overall average: 
49.28

Replacing all values below  40 with 0: 
[[  0   0   0   0  59]
 [ 68   0  67   0  96]
 [  0  89   0  82  62]
 [100  89  62  75  48]
 [ 43  58  69   0   0]]

Total marks added: 
[[  0   0   0   0  59  59]
 [ 68   0  67   0  96 231]
 [  0  89   0  82  62 233]
 [100  89  62  75  48 374]
 [ 43  58  69   0   0 170]]

1-D array: 
[  0   0   0   0  59  68   0  67   0  96   0  89   0  82  62 100  89  62
  75  48  43  58  69   0   0]


# EXAM


In [3]:
#Create a NumPy array containing numbers from 1 to 10.
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
#Create a 2D NumPy array with 3 rows and 3 columns filled with zeros.
arr=np.zeros((3,3), dtype=int)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [7]:
#Extract the first 3 elements from this array:
arr = np.array([10, 20, 30, 40, 50])
arr[:3]

array([10, 20, 30])

In [8]:
#Write code to extract the second row only.
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
arr[1,:]

array([4, 5, 6])

In [9]:
#Extract only the first column.
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
arr[:,0]

array([1, 4, 7])

In [13]:
#Write code to extract all EVEN numbers using Boolean filtering.
arr = np.array([5, 12, 23, 4, 19, 8])
arr[arr%2==0]

array([12,  4,  8])

In [14]:
#Add 5 to each element using vectorization (no loops).
arr = np.array([[10, 20, 30],
                [40, 50, 60]])
arr+5

array([[15, 25, 35],
       [45, 55, 65]])

In [15]:
#Reshape the array into a 3×2 matrix.
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
#Stack a new column [10, 20, 30] to the right side of the array.
arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])
np.hstack((arr, np.array([10,20,30]).reshape(3,1)))

array([[ 1,  2, 10],
       [ 3,  4, 20],
       [ 5,  6, 30]])

In [19]:
#Find the sum of each COLUMN.
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
arr.sum(axis=0)

array([120, 150, 180])

In [13]:
#Replace all values LESS than 10 with 0.
import numpy as np
arr = np.array([5, 12, 23, 4, 19, 8])
arr[arr < 10]=0

In [7]:
#Find the INDEX of the maximum value in the array.
arr = np.array([1, 5, 3, 9, 2, 8, 6])
np.argmax(arr)

np.int64(3)

In [11]:
#Flatten the array into a 1-D array WITHOUT using reshape.
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
#Extract the diagonal elements using a NumPy function (no slicing).
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
arr.diagonal()

array([1, 5, 9])

In [19]:
#Compute the matrix multiplication of arr with itself.
arr = np.array([[1, 2],
                [3, 4]])
c=arr@arr
print(c)

[[ 7 10]
 [15 22]]


In [4]:
#1) Replace all ODD numbers with -1
#2) Find the row-wise maximum
#3) Flatten the array
import numpy as np
arr = np.random.randint(1, 50, size=(4,4))
print(arr)

arr[arr%2==1]=-1
print(arr)

print("Row wise max")
print(arr.max(axis=1))

print("Flatten the array")
arr.flatten()

[[ 1 27 19  8]
 [35 24 37 43]
 [41  7 44 23]
 [33 18  9 41]]
[[-1 -1 -1  8]
 [-1 24 -1 -1]
 [-1 -1 44 -1]
 [-1 18 -1 -1]]
Row wise max
[ 8 24 44 18]
Flatten the array


array([-1, -1, -1,  8, -1, 24, -1, -1, -1, -1, 44, -1, -1, 18, -1, -1],
      dtype=int32)

In [13]:
#Extract the last two rows
#Extract the last two columns
# Extract this block:
#[[6 7]
#[10 11]]
arr = np.arange(1, 17).reshape(4,4)
print(arr)
print()

r=arr[-2:,:]
print(r)
print()

c=arr[:,-2:]
print(c)
print()

d=arr[1:3,1:3]
print(d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 9 10 11 12]
 [13 14 15 16]]

[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]

[[ 6  7]
 [10 11]]


In [37]:
np.random.seed(4)

arr=np.random.randint(0,101, size=(5,5))
print(arr)
print()

m=np.mean(arr)
print("Mean: ",m)
print()

c=arr.copy()

c[c<m]=-1
print(c)
print()

print("Extract ONLY the values in the array that are divisible by 5")
d=arr[arr%5==0]
print(d)
print()

arr.reshape(25,1)
print(arr)
print()

print("Find the row index of the row with the HIGHEST sum")
array=np.sum(arr,axis=1)
np.argmax(array)

[[46 55 69  1 87]
 [72 50  9 58 94]
 [55 55 57 36 50]
 [44 38 52  3  0]
 [55 21 21 73 38]]

Mean:  45.56

[[46 55 69 -1 87]
 [72 50 -1 58 94]
 [55 55 57 -1 50]
 [-1 -1 52 -1 -1]
 [55 -1 -1 73 -1]]

Extract ONLY the values in the array that are divisible by 5
[55 50 55 55 50  0 55]

[[46 55 69  1 87]
 [72 50  9 58 94]
 [55 55 57 36 50]
 [44 38 52  3  0]
 [55 21 21 73 38]]

Find the row index of the row with the HIGHEST sum


np.int64(1)